### ISSUE TITLE
Pull-merge runs in merge queue

### ISSUE THREAD

**Issue by goodov** [brave/workflows#8]
Pull-merge analyzes the pull request and adds a comment with the short description. I don't think it make sense to run this as a part of the merge queue.

@thypon this trigger should be removed: https://github.com/brave/workflows/blob/0f44140ffe7e08b45374cdee5178bd38bd2894ec/.github/workflows/pull-merge.yml#L5

**Comment by goodov** [comment]
found it here https://github.com/brave/brave-variations/actions/runs/10488295956

![image](https://github.com/user-attachments/assets/677c1c37-24a7-4308-8ec3-8332fe2f9a3c)

**Comment by thypon** [comment]
This was added since it was crashing/blocking any merge-queue. Unfortunately it is a github limitation workaround.
